src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Twitter_User__c</fullName>
        <label>Twitter User</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Twitter_User__c</fullName>
        <label>Twitter User</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Speaker__c.object
<CustomObject>
    <fields>
        <fullName>Biography__c</fullName>
        <label>Biography</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Speakers</relationshipLabel>
        <relationshipName>Speakers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Speakers</relationshipLabel>
        <relationshipName>Speakers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Speaker_Name__c</fullName>
        <label>Speaker Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Speaker</label>
    <nameField>
        <displayFormat>SPKR-{000000}</displayFormat>
        <label>Speaker Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Speaker_Slot__c.object
<CustomObject>
    <fields>
        <fullName>Session__c</fullName>
        <label>Session</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>Speaker Slots</relationshipLabel>
        <relationshipName>Speaker_Slots</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Speaker_Name__c</fullName>
        <formula>HYPERLINK(&quot;/&quot;+ Speaker__r.Id ,  Speaker__r.Speaker_Name__c ,&quot;_self&quot;)</formula>
        <label>Speaker Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Speaker__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Speaker</label>
        <referenceTo>Speaker__c</referenceTo>
        <relationshipLabel>Speaker Slots</relationshipLabel>
        <relationshipName>Speaker_Slots</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Speaker Slot</label>
    <nameField>
        <displayFormat>SS-{00000000}</displayFormat>
        <label>Speaker Slot Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Speaker Slots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EventFlexServices.cls
global with sharing class EventFlexServices {
	@remoteAction
	global static Map<String, List<Topic>> getSessionTopics(String eventId){

		List<TopicAssignment> topicAssigments = new List<TopicAssignment>();
		Map<String, List<Topic>> temp = new Map<String, List<Topic>>();

		for(TopicAssignment ta : [select id, TopicId, EntityId, Topic.Description, Topic.Name, Topic.TalkingAbout from TopicAssignment where EntityId in (select id from Session__c where Event__c = : eventId)]){
			Topic tt = new Topic(id = ta.TopicId, Description = ta.topic.Description, Name = ta.Topic.Name);

			if(temp.containsKey(ta.EntityId)){
				temp.get(ta.EntityId).add(tt);
			}else{
				temp.put(ta.EntityId, new List<Topic>{tt});
			}
		}

		return temp;
	}

	@remoteAction
	global static Map<String, List<Speaker__c>> getSessionSpeakers(String eventId){

		
		Map<String, List<Speaker__c>> temp = new Map<String, List<Speaker__c>>();

		for(Speaker_Slot__c sl : [select id, Speaker_Name__c, Speaker__r.Speaker_Name__c, Speaker__r.Biography__c, Session__c, Speaker__r.Contact__c, Speaker__r.Contact__r.Name, Speaker__r.Contact__r.twitter_user__c, Speaker__c from Speaker_Slot__c where Session__r.Event__c = :eventId]){
			Speaker__c s = new Speaker__c(id = sl.Speaker__c, Speaker_Name__c = sl.Speaker__r.Speaker_Name__c, Biography__c = sl.Speaker__r.Biography__c, Contact__c = sl.Speaker__r.Contact__c);

			if(temp.containsKey(sl.Session__c)){
				temp.get(sl.Session__c).add(s);
			}else{
				temp.put(sl.Session__c, new List<Speaker__c>{s});
			}
		}

		return temp;
	}

}