src/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Twitter_User__c</fullName>
        <label>Twitter User</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Social_Post__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Social Posts</relationshipLabel>
        <relationshipName>Social_Posts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Post_text__c</fullName>
        <label>Post text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Social_User__c</fullName>
        <label>Social User</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Twitter</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Social Post</label>
    <nameField>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>Social Post Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Social Posts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EventTweetFeedController.cls
public with sharing class EventTweetFeedController {

    public String newTweet{get;set;}
    public String result {get;set;}
    public SimpleTweet.TwitterSearchResponse searchResponse {get;set;}
    public String twitterSearch {get;set;}
    public Event__c event {get;set;}
    public boolean showTweet{get;set;}
    
    private Id eventId;
    private String twitterUser; 
    
   
  
   public EventTweetFeedController(ApexPages.StandardController controller) {
       loadData(controller);
    
    } 
    
    private void loadData(ApexPages.StandardController controller){
      
      if(eventId==null){
         eventId= (Id)controller.getId();
      }
      if(this.event == null){ 
        this.event = getEventDetail(eventId);
      }
      twitterUser = event.Twitter_User__c  ;
      searchResponse = SimpleTweet.search(twitterUser, 20);
      showTweet = false;
    } 
    
    private Event__c  getEventDetail(Id eventId){
      Event__c   ev = [ SELECT id, name , Twitter_User__c  FROM Event__c where id =:eventId ];
       return ev ;
    }
/*    
    public EventTweetFeedController(){
        searchResponse = SimpleTweet.search('EventAcu', 20);
    }
*/
 /*   public void postTweet(){
       SimpleTwitterPost twitter = new SimpleTwitterPost();
        if (twitter.tweet(newTweet)){
            result = 'Tweeted';
        } 
    }
*/
    public void search(){
         showTweet=true;
         System.debug('***********showTweet*************' + showTweet);
         System.debug('***********twitterUser *************' + twitterUser );
        searchResponse = SimpleTweet.search(event.Twitter_User__c, 20);
        
        System.debug('***********searchResponse *************' + searchResponse);
         System.debug('***********searchResponse.statuses *************' + searchResponse.statuses);
    }
    
    public void createSocialPost(){
      System.debug('***********searchResponse *************' + searchResponse);
      System.debug('***********searchResponse.statuses *************' + searchResponse.statuses);
      List<Social_Post__c > socialPostList = new List<Social_Post__c >();
      for( Tweet tw : searchResponse.statuses){
          String id = tw.id_str ;
          String text = tw.text;
          
          System.debug('***********id*************' + id);
          System.debug('***********text *************' + text );
             Social_Post__c sPost =  New Social_Post__c ();
             sPost.External_ID__c = tw.id_str;
             sPost.Post_text__c= tw.text;
             sPost.Type__c='Twitter';
             sPost.Event__c = eventId;
             sPost.Social_User__c = tw.user.name;
             socialPostList.add(sPost);
      }
     //  insert socialPostList;
      Database.SaveResult[] saveResult = Database.Insert(socialPostList,false);
      
     
    }

}